### ISSUE TITLE
New Error Latest Updated

### ISSUE THREAD

**Issue by rossman22590** [snekkenull/Anthropic-Claude-demo#5]
Anthropic API Error:  ReferenceError: XMLHttpRequest is not defined
    at (entry.mjs:29:9525)
    at (entry.mjs:29:9393)
    at (entry.mjs:33:317)
    at (entry.mjs:29:11148)
    at (entry.mjs:29:10945)
    at (entry.mjs:33:257)
    at (entry.mjs:172:48

**Comment by snekkenull** [comment]
Thanks your info, I will check it.

**Comment by rossman22590** [comment]
please and ty

**Comment by rossman22590** [comment]
any idea how to solve? the whole app stopped working

**Comment by snekkenull** [comment]
It works in netlify, something wrong by vercel. Because chatgpt-demo update v2 which support plugins, I would merge it recently.

**Comment by rossman22590** [comment]
same issue here: https://ephemeral-caramel-c5e48d.netlify.app/

**Comment by rossman22590** [comment]
Apr 25, 12:36:49 PM: error  [entry] Error: Sampling error: 401 Unauthorized
    at Client.<anonymous> (file:///root/.netlify/edge-functions/entry.js:69157:24)
    at Generator.next (<anonymous>)
    at fulfilled (file:///root/.netlify/edge-functions/entry.js:69103:24)Apr 25, 12:36:49 PM: error  [entry] Anthropic API Error:  Error: Sampling error: 401 Unauthorized
    at Client.<anonymous> (file:///root/.netlify/edge-functions/entry.js:69157:24)
    at Generator.next (<anonymous>)
    at fulfilled (file:///root/.netlify/edge-functions/entry.js:69103:24)Apr 25, 12:36:49 PM: error  [entry] Anthropic API Error:  Error: Sampling error: 401 Unauthorized
    at Client.<anonymous> (file:///root/.netlify/edge-functions/entry.js:69157:24)
    at Generator.next (<anonymous>)
    at fulfilled (file:///root/.netlify/edge-functions/entry.js:69103:24)Apr 25, 12:36:49 PM: info   [entry] 04:36:49 PM [ssr] Setting headers is not supported when returning an object. Please return an instance of Response. See https://docs.astro.build/en/core-concepts/endpoints/#server-endpoints-api-routes for more information.

**Comment by snekkenull** [comment]
Thanks for your log.
I have updated to fix the  [ssr] Setting headers is not supported when returning an object. And works well in my netlify.
But the 401 Unauthorized looks the problem of Anthropic API.

**Comment by rossman22590** [comment]
what update is this?  Bacause chatgpt-demo update v2 which support plugins,
I would merge it recently.

**Comment by rossman22590** [comment]
fixed!
